# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '**/Dockerfile'
        tags: |
          $(tag)
    - task: CopyFiles@1
      displayName: 'Copy Files to: $(build.artifacstagingdirectory)'
      inputs: 
        SourceFolder: :'$(build.sourcedirectory)'
        Contents: |
          **\bin\$(BuildConfiguration)\**
          src\*.testsettings
        TargetFolder: '$(build.artifactstagingdirectory)'
      condition: succededOrFailed()

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(build.artifacstagingdirectory)'
      condition: succededOrFailed()